# Generated by Django 5.2.4 on 2025-07-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(default="", max_length=100)),
                ("department", models.ManyToManyField(to="Organizations.department")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
