# Generated by Django 5.2.4 on 2025-07-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Organizations", "0002_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(default="", max_length=100)),
                ("event_description", models.TextField()),
                ("event_venue", models.CharField(default="", max_length=100)),
                ("handler", models.ManyToManyField(to="Organizations.organization")),
            ],
        ),
    ]
