# Generated by Django 5.2.4 on 2025-07-15 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time_in",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 15, 17, 15, 5, 551850)
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="time_out",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 15, 17, 15, 5, 551881)
            ),
        ),
    ]
