# Generated by Django 5.2.4 on 2025-07-16 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_rename_participant_info_participant_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 12, 42, 14, 377167)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 12, 42, 14, 377167)),
        ),
    ]
