# Generated by Django 5.2.4 on 2025-07-16 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_alter_event_time_in_alter_event_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='time_in',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 13, 37, 25, 345945)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 13, 37, 25, 345945)),
        ),
    ]
