# Generated by Django 5.2.4 on 2025-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.CharField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
