# Generated by Django 5.2.4 on 2025-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-time_in']},
        ),
        migrations.AddField(
            model_name='participant',
            name='time_out',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='time_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
