# Generated by Django 5.2.4 on 2025-07-16 03:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_time_in_event_time_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 11, 34, 53, 749448)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 11, 34, 53, 750458)),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('participant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
