# Generated by Django 5.2.4 on 2025-07-16 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_event_time_in_alter_event_time_out_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='participant_name',
            new_name='participant_info',
        ),
        migrations.AlterField(
            model_name='event',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 11, 49, 7, 446667)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 11, 49, 7, 446667)),
        ),
    ]
