# Generated by Django 5.2.4 on 2025-07-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_participant_options_participant_time_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='time_out',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
