# Generated by Django 5.2.4 on 2025-07-16 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_rename_participant_name_participant_participant_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='participant_info',
            new_name='participant',
        ),
        migrations.AlterField(
            model_name='event',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 12, 15, 46, 574146)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 12, 15, 46, 574146)),
        ),
    ]
