# Generated by Django 5.2.4 on 2025-07-20 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0007_participant_time_in_alter_event_time_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time_in",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 20, 2, 17, 18, 534699)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_out",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 20, 2, 17, 18, 534816)
            ),
        ),
    ]
