# Generated by Django 5.2.4 on 2025-07-20 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0009_alter_event_time_in_alter_event_time_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time_in",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 20, 5, 1, 29, 146932)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_out",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 20, 5, 1, 29, 146961)
            ),
        ),
    ]
