# Generated by Django 5.2.4 on 2025-07-20 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0010_alter_event_time_in_alter_event_time_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time_in",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 20, 13, 44, 47, 557155)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_out",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 20, 13, 44, 47, 557190)
            ),
        ),
    ]
