# Generated by Django 5.2.4 on 2025-07-24 19:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0014_alter_event_time_in_alter_event_time_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time_in",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 24, 19, 2, 27, 315343)
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_out",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 24, 19, 2, 27, 315369)
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Events.event"
            ),
        ),
    ]
