# Generated by Django 5.2.4 on 2025-08-01 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0004_alter_participant_time_in_alter_participant_time_out"),
        ("Feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="event",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Events.event",
            ),
        ),
    ]
