# Generated by Django 5.2.4 on 2025-08-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Feedbacks", "0002_feedback_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="title",
        ),
    ]
