# Generated by Django 5.2.4 on 2025-08-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Feedbacks", "0003_remove_feedback_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="message",
            new_name="mesasge",
        ),
    ]
