# Generated by Django 5.2.4 on 2025-08-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Feedbacks", "0004_rename_message_feedback_mesasge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="mesasge",
            new_name="message",
        ),
    ]
