# Generated by Django 5.2.4 on 2025-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(default="", max_length=100)),
                ("organization_name", models.CharField(default="", max_length=100)),
                (
                    "department",
                    models.ManyToManyField(default="", to="Departments.department"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
