# Generated by Django 5.2.4 on 2025-07-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(default="", max_length=100)),
                ("organization_name", models.CharField(default="", max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
