# Generated by Django 5.2.4 on 2025-07-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0001_initial"),
        ("Organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="department",
            field=models.ManyToManyField(to="Departments.department"),
        ),
    ]
