# Generated by Django 5.2.4 on 2025-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organizations", "0002_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organization_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
