# Generated by Django 5.2.4 on 2025-07-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0001_initial"),
        ("Organizations", "0002_organization_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="department",
            field=models.ManyToManyField(default="", to="Departments.department"),
        ),
    ]
