# Generated by Django 5.2.4 on 2025-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_user_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verified",
        ),
        migrations.AddField(
            model_name="student",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
