# Generated by Django 5.2.4 on 2025-07-20 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0012_alter_user_options"),
        ("Organizations", "0002_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="Organizations.department",
            ),
        ),
    ]
