# Generated by Django 5.2.4 on 2025-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(default='BS', max_length=10)),
                ('department_name', models.CharField(default='Bachelor of Science in ', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
