# Generated by Django 5.2.4 on 2025-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='875f8b48ca75414cb96355dc9ffde8c6', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
