# Generated by Django 5.2.4 on 2025-07-15 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='f8b810fac7114881829f6d4c3bbd3b5e', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(default='012A-1234', max_length=25, primary_key=True, serialize=False, unique=True)),
                ('student_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
