# Generated by Django 5.2.4 on 2025-07-15 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0008_remove_user_verified_student_verified"),
        ("Organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="Organizations.department",
            ),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
