# Generated by Django 5.2.4 on 2025-07-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0009_alter_user_department_delete_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["-student_id"]},
        ),
    ]
