# Generated by Django 5.2.4 on 2025-07-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_user_verified_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username']},
        ),
    ]
